### ISSUE TITLE
Great plugin! minor issue with symlinks that are missing

### ISSUE THREAD

**Issue by thomasvangurp** [bhofmei/jbplugin-nucdens#2]
Dear Brigitte,

The plugin works great. It does not work out of the box though, I had to make 2 symlinks:
1. Make a symlink called NucleotideDensityPlugin
```ln -s jbplugin-nucdens NucleotideDensityPlugin```
2. Inside plugins/NucleotideDensityPlugin make a symlink to View:
```ln -s js/View/```

Cheers,
Thomas

**Comment by bhofmei** [comment]
It seems you did not install the repository as is suggested by the README. 

When calling `git clone`, there's an optional parameter for the new file name. When not included, it defaults to the repository name. Instead of making the symlink, you could

1. rename the _jbplugin-nucdens_ folder to _NucleotideDensityPlugin_
2. reclone the repository using `git clone https://github.com/bhofmei/jbplugin-nucdens.git NucleotideDensityPlugin` as specified in the README
or
3. change the location of the plugin in _jbrowse.conf_ to `location = plugins/jbplugin-nucdens`

I'm guessing the symlink for `js/View` was necessary due to the installation problem mentioned above. If you ran into this error when creating the nucleotide density track, another way around this is to use `"type":"NucDensity"` instead of `"type": "NucleotideDensityPlugin/View/Track/NucleotideDensity"` in the track configuration.
